addpath('../script');
addpath('../script/ar-gmm');
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/201.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/201.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/201.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/215.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/215.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/215.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/224.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/224.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/224.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/244.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/244.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/244.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/260.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/260.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/260.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/269.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/269.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/269.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/275.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/275.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/275.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/283.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/283.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/283.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/290.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/290.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/290.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/295.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/295.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/295.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/302.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/302.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/302.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/316.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/316.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/316.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/321.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/321.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/321.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/330.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/330.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/330.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/341.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/341.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/341.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/344.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/344.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/344.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/352.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/352.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/352.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/361.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/361.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/361.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/376.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/376.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/376.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/381.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/381.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/381.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/395.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/395.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/395.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/403.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/403.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/403.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/414.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/414.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/414.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/421.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/421.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/421.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/432.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/432.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/432.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/441.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/441.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/441.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/456.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/456.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/456.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/461.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/461.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/461.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/478.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/478.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/478.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
fprintf('converting ../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/489.wav.org.mcep \n ');
fd=fopen('../vc/train/tosad_ar/test/64-mix/wav/convert-1/489.mcep.txt','w');
fp=fopen('../vc/train/tosad_ar/test/64-mix/wav/neutral-sad_64mix/489.wav.org.mcep','rb');
x=fread(fp,inf,'float32');
fclose(fp);
T=size(x,1)/25;
 x=reshape(x,25,T);
predict=gmm_ar_ABdiag_convert(x,48,1,1,64,'../vc/train/tosad_ar/gmm_para/64-mix/neutral-sad64_ordery1_fullbt.para.txt','spBfull');
fprintf(fd,'%f\n',predict);
fclose(fd);
